_target_: src.models.m_3d_unet.UnetModule
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.unet3d.UnetModel
  in_channels: 1
  out_channels: 1
# compile model for faster training with pytorch 2.0
compile: false
